### ISSUE TITLE
Install Fails Because Microsoft Download File No Longer Available

### ISSUE THREAD

**Issue by c3yvonne7** [LearnLift/MemoryLifter#1]
Memory Lifter fails to install and gives the following error message The install file was from https://download.cnet.com/MemoryLifter/3000-2279_4-10235406.html.

An error occurred downloading the following resource:
http://go.microsoft.com/fwlink/?LinkId=166086&clcid=0x409

Here is the log file:
[memorylifterlog.txt](https://github.com/LearnLift/MemoryLifter/files/4309839/memorylifterlog.txt)

**Comment by chrfin** [comment]
Hi,
thanks for submitting this issue - it seems Microsoft deleted the SQLCE-Runtime installer from their servers. I'll check if I can find another location to get it from (you can install it manually before installing MemoryLifter and then the setup should succeed)...

**Comment by chrfin** [comment]
The problem was already reported to Microsoft, but it seems it is not fixed yet:
https://developercommunity.visualstudio.com/content/problem/935924/sql-server-compact-35-sp2-download-link-is-invalid.html

**Comment by c3yvonne7** [comment]
I installed Microsoft® SQL Server® Compact 4.0 SP1 from https://www.microsoft.com/en-us/download/details.aspx?id=30709 (64 bit version) using the SSCERuntime_x64-ENU.exe file,  but MemoryLifter still won't install (same error message as before).

**Comment by chrfin** [comment]
MemoryLifter needs SQL CE 3.5 SP2, which is not compatible with 4.0...

**Comment by c3yvonne7** [comment]
Hi Chrfin,

Thanks so much for your help. I managed to find SQL CE 3.5 SP2 at 
https://www.microsoft.com/en-us/download/details.aspx?id=5783
After extracting and installing both x86 and 64 bit versions as per the instructions, Memory Lifter installed without any trouble.

**Comment by chrfin** [comment]
For anyone facing the same problem please also manually install like @c3yvonne7.  
Closing this for now.
