### ISSUE TITLE
Pre-made Learning Modules: Anyone have copies or archive?

### ISSUE THREAD

**Issue by RLithgow** [LearnLift/MemoryLifter#2]
I've been a fan of Memory Lifter since around 2007 or 2008, and have gone back to it on and off over the years. I'm now trying to use it for my young child. Would anyone by chance have a collection of the old pre-made memory lifter modules that were once free and publicly available from the Learn Lift website? I'm looking all over for them online but can't find them anywhere.

**Comment by chrfin** [comment]
I need to check in the office what/if we have them still around, but as we are working from home at the moment this could take a few weeks...

**Comment by RLithgow** [comment]
I understand the difficulty and delay. Politely letting you know that I’m still here watching and patiently waiting in the hopes of recovering even a portion of what was once a vast library and catalog of memory lifter modules spanning a wide array of topics. Our schools shut down here in Illinois and I had hoped to use the premade modules for my son in kindergarten through the Spring and Summer. We still used Memory Lifter, but made our own cards. I made hundreds and thousands of flashcards in college using not outdated and unusable palm pilot programs, and even though Memory Lifter makes card creation FAR easier (and is much easier to use to import bulk lists once formatted properly) than many competing software of that era, I continued to swear by memory lifter once I’d stumbled across it. I regret not downloading every module one by one when I had the chance. I myself would still like to go through some of what was in that library, even though school, college, and law school are long behind me, as I found going through the cards aiming for mastery (using the system Memory Lifter Employs) feels therapeutic to this life-long patient and sufferer of ADHD (it’s almost like meditating, it’s like brain exercise for me). Making my own cards is time consuming, although I’m more than willing to continue doing that; I’d just prefer not to reinvent the wheel when it comes to the data entry, and there were more topics and cards in the original plethora on the website than I’d ever be able to create myself and utilize all of the wonderful features of the software far more fully than I could manage on my own without examples to work from. And, I’d still like to pick out some of the topics that might be of use to my son (now in first grade) who’s reduced to e-learning from home (although the local school teachers are working very hard and doing an impressive job making that work as best they can). I know the world is in some odd circumstances right now, and I suspect Memory Lifter is more of a shelved side-project now. But if you do happen to come across the original library of modules, or even just a small portion of that library (whatever you come across and can get your hands on), I’d be very grateful if you could pass it along my way, if it isn’t too much trouble.

On another note, I sincerely hope you, your family, friends, co-workers and countrymen remain in good health as our world waits for this pandemic mess to pass and life to return to normal.

Very best wishes,
Robert Lithgow
RLithgow@LithgowLaw.com<mailto:RLithgow@LithgowLaw.com>

Schaumburg, Illinois, USA

**Comment by chrfin** [comment]
@RLithgow Thanks for the reminder, please see https://github.com/LearnLift/LearningModules for all modules I could find right now...
